---
# Playbook to install the Jekyll gem, and clone the blog's repo

- hosts: all
  remote_user: vagrant

  tasks:

    - name: Install Extra Packages for Enterprise Linux (EPEL)
      yum: name=epel-release state=latest
      become: true

    - name: Install Ruby
      yum: name=ruby state=latest
      become: true

    - name: Install Ruby development packages
      yum: name=ruby-devel state=latest
      become: true

    - name: Install Ruby gems
      yum: name=rubygems state=latest
      become: true

    - name: Install NPM
      yum: name=npm state=latest
      become: true

    - name: Install github-pages Ruby gem
      gem: name=github-pages state=latest
 
    - name: Install Git
      yum: name=git state=latest
      become: true
    
    - name: Install Vim text editor
      yum: name=vim state=latest
      become: true

    - name: Clone github repo
      become: false
      git: repo=https://github.com/MrThePlague/mrtheplague.github.io.git dest=~/mrtheplague.github.io
