---
# Playbook to install the Jekyll gem, and clone the blog's repo

- hosts: all
  remote_user: vagrant

  tasks:

    - name: Install Extra Packages for Enterprise Linux (EPEL)
      yum: name=epel-release state=latest
      sudo: True

    - name: Install Ruby
      yum: name=ruby state=latest
      sudo: True

    - name: Install Ruby development packages
      yum: name=ruby-devel state=latest
      sudo: True

    - name: Install Ruby gems
      yum: name=rubygems state=latest

    - name: Install NodeJS
      yum: name=nodejs state=latest
      sudo: True

    - name: Install NPM
      yum: name=npm state=latest
      sudo: True

    - name: Install rdiscount ruby gem
      gem: name=rdiscount state=latest
    
    - name: Install Redcarpet
      gem: name=redcarpet state=latest

    - name: Install Jekyll
      gem: name=jekyll state=latest
    
    - name: Install Jekyll-Paginate
      gem: name=jekyll-paginate state=latest

    - name: Install rouge
      gem: name=rouge state=latest

    - name: Install Git
      yum: name=git state=latest
      sudo: True
    
    - name: Install Vim text editor
      yum: name=vim state=latest
      sudo: True

    - name: Clone github repo
      sudo: False
      git: repo=https://github.com/MrThePlague/mrtheplague.github.io.git dest=~/mrtheplague.github.io
